/**
 * Section Blueprint — Canonical definition of all onboarding sections
 *
 * Single source of truth for:
 * - Which sections exist and their display order
 * - What discovery facts each section requires
 * - Quality thresholds (minimal / good / excellent)
 *
 * Imported by:
 * - server/src/lib/slot-machine.ts (readiness computation)
 * - server/src/agent-v2/deploy/tenant/src/prompts/system.ts (section blueprint table)
 * - server/src/services/context-builder.service.ts (bootstrap data)
 *
 * @see docs/plans/2026-02-06-feat-dashboard-onboarding-rebuild-plan.md (Phase 3.2)
 */

// ============================================================================
// Types
// ============================================================================

/** Quality level based on how many facts are available for a section */
export type SectionQuality = 'minimal' | 'good' | 'excellent';

/** Readiness status for a single section */
export interface SectionReadiness {
  /** Lowercase section type matching BlockType (e.g., 'hero', 'about') */
  sectionType: string;
  /** Whether the minimum required facts are present */
  isReady: boolean;
  /** Fact keys that ARE available for this section */
  knownFacts: string[];
  /** Fact keys that are missing but relevant */
  missingFacts: string[];
  /** Quality assessment based on available facts */
  quality: SectionQuality;
}

/** Blueprint definition for a single section type */
export interface SectionBlueprintEntry {
  /** Lowercase section type (matches slot machine keys) */
  sectionType: string;
  /** Display order (1-based, matches system prompt table) */
  order: number;
  /** Human label for the section */
  label: string;
  /**
   * Required fact groups (AND logic between groups, OR logic within each group).
   * Each inner array is an OR-group: at least one key must be present.
   * All OR-groups must pass for the section to be "ready".
   */
  requiredFacts: string[][];
  /** Nice-to-have facts that improve quality but aren't required */
  optionalFacts: string[];
  /** Priority: MUST = core section, SHOULD = important, IDEAL = bonus */
  priority: 'MUST' | 'SHOULD' | 'IDEAL';
  /** The question the agent should ask to fill this section (natural language) */
  agentQuestion: string;
  /** Whether this section is auto-generated (no direct question needed) */
  autoGenerated: boolean;
  /** Whether this section is shown during the initial "wow moment" reveal */
  isRevealMVP: boolean;
}

// ============================================================================
// Canonical Section Blueprint (8 sections matching slot machine)
// ============================================================================

/**
 * The 8 canonical sections for onboarding.
 *
 * Order matters — this defines the guided review sequence when the agent
 * walks the tenant through their site after the reveal.
 */
export const SECTION_BLUEPRINT: readonly SectionBlueprintEntry[] = [
  {
    sectionType: 'hero',
    order: 1,
    label: 'Hero',
    requiredFacts: [['businessType']],
    optionalFacts: ['targetMarket', 'uniqueValue', 'location'],
    priority: 'SHOULD',
    agentQuestion: 'What do you do, and who do you do it for?',
    autoGenerated: false,
    isRevealMVP: true,
  },
  {
    sectionType: 'about',
    order: 2,
    label: 'About',
    requiredFacts: [['businessType'], ['uniqueValue', 'approach']],
    optionalFacts: ['yearsInBusiness', 'teamSize'],
    priority: 'SHOULD',
    agentQuestion: 'Give me the short version of your story.',
    autoGenerated: false,
    isRevealMVP: true,
  },
  {
    sectionType: 'services',
    order: 3,
    label: 'Services',
    requiredFacts: [['servicesOffered']],
    optionalFacts: ['specialization', 'priceRange'],
    priority: 'MUST',
    agentQuestion: 'Walk me through what you offer.',
    autoGenerated: false,
    isRevealMVP: true,
  },
  {
    sectionType: 'pricing',
    order: 4,
    label: 'Pricing',
    requiredFacts: [['servicesOffered'], ['priceRange']],
    optionalFacts: [],
    priority: 'IDEAL',
    agentQuestion: '', // Built from services — clarify if detailed tiers needed
    autoGenerated: true,
    isRevealMVP: false,
  },
  {
    sectionType: 'testimonials',
    order: 5,
    label: 'Testimonials',
    requiredFacts: [['testimonial']],
    optionalFacts: [],
    priority: 'IDEAL',
    agentQuestion: 'Got a favorite client quote? Even a text message works.',
    autoGenerated: false,
    isRevealMVP: false,
  },
  {
    sectionType: 'faq',
    order: 6,
    label: 'FAQ',
    requiredFacts: [['businessType'], ['servicesOffered']],
    optionalFacts: ['faq'],
    priority: 'IDEAL',
    agentQuestion: '', // Auto-generated from business context
    autoGenerated: true,
    isRevealMVP: false,
  },
  {
    sectionType: 'contact',
    order: 7,
    label: 'Contact',
    requiredFacts: [['businessType']],
    optionalFacts: ['contactInfo', 'location'],
    priority: 'SHOULD',
    agentQuestion: 'Where do people find you?',
    autoGenerated: false,
    isRevealMVP: false,
  },
  {
    sectionType: 'cta',
    order: 8,
    label: 'CTA',
    requiredFacts: [['businessType']],
    optionalFacts: ['targetMarket'],
    priority: 'SHOULD',
    agentQuestion: '', // Mirrors hero — no extra question
    autoGenerated: true,
    isRevealMVP: false,
  },
] as const;

/** Count of MVP sections for reveal threshold (used by AgentPanel.tsx) */
export const MVP_REVEAL_SECTION_COUNT = SECTION_BLUEPRINT.filter((s) => s.isRevealMVP).length;

/** Set of uppercase MVP section types (used for filtering) */
export const MVP_REVEAL_SECTION_TYPES = new Set(
  SECTION_BLUEPRINT.filter((s) => s.isRevealMVP).map((s) => s.sectionType.toUpperCase())
);

/**
 * Union of all canonical section type strings.
 *
 * SECTION_BLUEPRINT is typed as `readonly SectionBlueprintEntry[]` (sectionType: string),
 * so we define the literal union explicitly to enable autocomplete and narrowing.
 * Keep this in sync with the SECTION_BLUEPRINT entries above.
 */
export type CanonicalSectionType =
  | 'hero'
  | 'about'
  | 'services'
  | 'pricing'
  | 'testimonials'
  | 'faq'
  | 'contact'
  | 'cta';

/**
 * Section types as a flat array of strings.
 * Useful for validation and iteration.
 */
export const CANONICAL_SECTION_TYPES = SECTION_BLUEPRINT.map((s) => s.sectionType);

/**
 * Lookup map: sectionType → SectionBlueprintEntry
 *
 * Narrowed to Record<CanonicalSectionType, ...> so consumers get autocomplete
 * for valid section IDs (e.g., SECTION_BLUEPRINT_MAP['hero']) instead of
 * accepting arbitrary strings. Object.fromEntries() returns Record<string, V>,
 * so the assertion recovers the narrow key type.
 */
export const SECTION_BLUEPRINT_MAP = Object.fromEntries(
  SECTION_BLUEPRINT.map((s) => [s.sectionType, s])
) as Record<CanonicalSectionType, SectionBlueprintEntry>;

// ============================================================================
// Discovery Fact Labels (human-readable labels for each fact key)
// ============================================================================

/**
 * Human-readable labels for discovery fact keys.
 *
 * Single source of truth for the ComingSoon progress dots and any future
 * UI that shows fact-level labels. Derived from the same domain knowledge
 * as SECTION_BLUEPRINT but scoped to individual fact keys rather than sections.
 *
 * @see apps/web/src/components/preview/ComingSoonDisplay.tsx (consumer)
 * @see server/src/agent-v2/deploy/tenant/src/tools/discovery.ts (DISCOVERY_FACT_KEYS)
 */
export const DISCOVERY_FACT_LABELS: Readonly<Record<string, string>> = {
  businessType: 'What you do',
  businessName: 'Your business name',
  location: "Where you're based",
  targetMarket: 'Who you serve',
  priceRange: 'Your pricing',
  yearsInBusiness: 'Your experience',
  teamSize: 'Your team',
  uniqueValue: 'What sets you apart',
  servicesOffered: 'Your services',
  specialization: 'Your specialty',
  approach: 'Your approach',
  dreamClient: 'Your ideal client',
  testimonial: 'Client feedback',
  faq: 'Common questions',
  contactInfo: 'How to reach you',
};
