/**
 * Section Blueprint — Canonical definition of all onboarding sections
 *
 * Single source of truth for:
 * - Which sections exist and their display order
 * - What discovery facts each section requires
 * - Quality thresholds (minimal / good / excellent)
 *
 * Imported by:
 * - server/src/lib/slot-machine.ts (readiness computation)
 * - server/src/agent-v2/deploy/tenant/src/prompts/system.ts (section blueprint table)
 * - server/src/services/context-builder.service.ts (bootstrap data)
 *
 * @see docs/plans/2026-02-06-feat-dashboard-onboarding-rebuild-plan.md (Phase 3.2)
 */

// ============================================================================
// Types
// ============================================================================

/** Quality level based on how many facts are available for a section */
export type SectionQuality = 'minimal' | 'good' | 'excellent';

/** Readiness status for a single section */
export interface SectionReadiness {
  /** Lowercase section type matching BlockType (e.g., 'hero', 'about') */
  sectionType: string;
  /** Whether the minimum required facts are present */
  isReady: boolean;
  /** Fact keys that ARE available for this section */
  knownFacts: string[];
  /** Fact keys that are missing but relevant */
  missingFacts: string[];
  /** Quality assessment based on available facts */
  quality: SectionQuality;
}

/** Blueprint definition for a single section type */
export interface SectionBlueprintEntry {
  /** Lowercase section type (matches slot machine keys) */
  sectionType: string;
  /** Display order (1-based, matches system prompt table) */
  order: number;
  /** Human label for the section */
  label: string;
  /**
   * Required fact groups (AND logic between groups, OR logic within each group).
   * Each inner array is an OR-group: at least one key must be present.
   * All OR-groups must pass for the section to be "ready".
   */
  requiredFacts: string[][];
  /** Nice-to-have facts that improve quality but aren't required */
  optionalFacts: string[];
  /** Priority: MUST = core section, SHOULD = important, IDEAL = bonus */
  priority: 'MUST' | 'SHOULD' | 'IDEAL';
  /** The question the agent should ask to fill this section (natural language) */
  agentQuestion: string;
  /** Whether this section is auto-generated (no direct question needed) */
  autoGenerated: boolean;
}

// ============================================================================
// Canonical Section Blueprint (8 sections matching slot machine)
// ============================================================================

/**
 * The 8 canonical sections for onboarding.
 *
 * Order matters — this defines the guided review sequence when the agent
 * walks the tenant through their site after the reveal.
 */
export const SECTION_BLUEPRINT: readonly SectionBlueprintEntry[] = [
  {
    sectionType: 'hero',
    order: 1,
    label: 'Hero',
    requiredFacts: [['businessType']],
    optionalFacts: ['targetMarket', 'uniqueValue', 'location'],
    priority: 'SHOULD',
    agentQuestion: 'What do you do, and who do you do it for?',
    autoGenerated: false,
  },
  {
    sectionType: 'about',
    order: 2,
    label: 'About',
    requiredFacts: [['businessType'], ['uniqueValue', 'approach']],
    optionalFacts: ['yearsInBusiness', 'teamSize'],
    priority: 'SHOULD',
    agentQuestion: 'Give me the short version of your story.',
    autoGenerated: false,
  },
  {
    sectionType: 'services',
    order: 3,
    label: 'Services',
    requiredFacts: [['servicesOffered']],
    optionalFacts: ['specialization', 'priceRange'],
    priority: 'MUST',
    agentQuestion: 'Walk me through what you offer.',
    autoGenerated: false,
  },
  {
    sectionType: 'pricing',
    order: 4,
    label: 'Pricing',
    requiredFacts: [['servicesOffered'], ['priceRange']],
    optionalFacts: [],
    priority: 'IDEAL',
    agentQuestion: '', // Built from services — clarify if detailed tiers needed
    autoGenerated: true,
  },
  {
    sectionType: 'testimonials',
    order: 5,
    label: 'Testimonials',
    requiredFacts: [['testimonial']],
    optionalFacts: [],
    priority: 'IDEAL',
    agentQuestion: 'Got a favorite client quote? Even a text message works.',
    autoGenerated: false,
  },
  {
    sectionType: 'faq',
    order: 6,
    label: 'FAQ',
    requiredFacts: [['businessType'], ['servicesOffered']],
    optionalFacts: ['faq'],
    priority: 'IDEAL',
    agentQuestion: '', // Auto-generated from business context
    autoGenerated: true,
  },
  {
    sectionType: 'contact',
    order: 7,
    label: 'Contact',
    requiredFacts: [['businessType']],
    optionalFacts: ['contactInfo', 'location'],
    priority: 'SHOULD',
    agentQuestion: 'Where do people find you?',
    autoGenerated: false,
  },
  {
    sectionType: 'cta',
    order: 8,
    label: 'CTA',
    requiredFacts: [['businessType']],
    optionalFacts: ['targetMarket'],
    priority: 'SHOULD',
    agentQuestion: '', // Mirrors hero — no extra question
    autoGenerated: true,
  },
] as const;

/**
 * Section types as a flat array of strings.
 * Useful for validation and iteration.
 */
export const CANONICAL_SECTION_TYPES = SECTION_BLUEPRINT.map((s) => s.sectionType);

/**
 * Lookup map: sectionType → SectionBlueprintEntry
 */
export const SECTION_BLUEPRINT_MAP: Record<string, SectionBlueprintEntry> = Object.fromEntries(
  SECTION_BLUEPRINT.map((s) => [s.sectionType, s])
);
